### ISSUE TITLE
TypeError: url.URL is not a constructor

### ISSUE THREAD

**Issue by Shen-Yu** [nodecraft/b2-cloud-storage#34]
Hello, i'm using b2-cloud-storage npm package in my react-website，and run code like your Basic Example，but it's not work. how can i resolve this ? Thanks !

![image](https://user-images.githubusercontent.com/13065982/88249293-9f8b5e00-ccd6-11ea-890b-fff8d025db36.png)

![image](https://user-images.githubusercontent.com/13065982/88249273-8c788e00-ccd6-11ea-8566-0a99451a26f8.png)

**Comment by Cherry** [comment]
This library is currently only designed to work in a Node environment - not in the browser.

With a build chain you may be able to polyfill used Node libraries, but this makes heavy use of `fs`, as well as other node builtins like `os`.

**Comment by Shen-Yu** [comment]
@Cherry  yes, i'v wrote a web version: [B2Viewer](https://github.com/Shen-Yu/b2-viewer), It still has a lot of imperfections, such as Upload files and folder, you are right, it should make heavy use of `fs` and any other node modules.
